---
title: "Welcome my chilren"
date: 2019-09-12

author: The Last Surviving Genji Main
email: genjomain@gmail.com
description: Welcome, fellow japondas. We may be called many names lik, weeabou, anime lover,
             trash but my children.....I AM HERE TO PUT AN END TO ALL OF THIS DISCRIMINATION.
             JOIN THE REVOLUTION!!
theme: minima
# social links
blizzard_username: The45thSaber
PSN_username: The45thSaber
Marvel Insider_username: Saber
MCOC_username: Lunala62
github_username: WeeabouBoy
credit card credentials: 4206991121666
---
